package com.organizetrip.organizetripapplication.gui;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Locale;

import com.organizetrip.organizetripapplication.classes.UserInfo;
import com.organizetrip.organizetripapplication.components.datechooser.DateBetween;
import com.organizetrip.organizetripapplication.components.datechooser.DateChooser;
import com.organizetrip.organizetripapplication.components.datechooser.listener.DateChooserAction;
import com.organizetrip.organizetripapplication.components.datechooser.listener.DateChooserAdapter;

public class DatesAndTransportPanel extends javax.swing.JPanel {
    private UserInfo userInfo;
    private DateChooser chDate = new DateChooser(new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("es", "ES")), " al ");
    private boolean own = true;
    private boolean taxi = false;
    private boolean bus = false;

    /**
     * Creates new form DatesPanel
     */
    public DatesAndTransportPanel(UserInfo userInfo) {
        this.userInfo = userInfo;
        initComponents();
        defineDates();
        updateTransport();
    }

    private void updateTransport() {
        if (own) {
            rbOwn.setSelected(true);
            rbTaxi.setSelected(false);
            rbBus.setSelected(false);
            userInfo.setTransport("Auto propio");
        } else if (taxi) {
            rbOwn.setSelected(false);
            rbTaxi.setSelected(true);
            rbBus.setSelected(false);
            userInfo.setTransport("Taxi");
        } else if (bus) {
            rbOwn.setSelected(false);
            rbTaxi.setSelected(false);
            rbBus.setSelected(true);
            userInfo.setTransport("Bus");
        }
    }

    private void defineDates() {
        chDate.setTextField(txtDate);
        chDate.setDateSelectionMode(DateChooser.DateSelectionMode.BETWEEN_DATE_SELECTED);
        chDate.setDateFormat(new SimpleDateFormat("dd 'de' MMMM 'de' yyyy", new Locale("es", "ES")));
        // chDate.setLabelCurrentDayVisible(false);
        chDate.addActionDateChooserListener(new DateChooserAdapter() {
            @Override
            public void dateBetweenChanged(DateBetween dateBetween, DateChooserAction action) {
                // Formato en la base de datos
                SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                String from = df.format(dateBetween.getFromDate());
                String to = df.format(dateBetween.getToDate());
                userInfo.setStartDate(LocalDate.parse(from));
                userInfo.setEndDate(LocalDate.parse(to));
                
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        bg = new javax.swing.JPanel();
        pnContent = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblTitle2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbOwn = new com.organizetrip.organizetripapplication.components.radio_button.RadioButtonCustom();
        rbTaxi = new com.organizetrip.organizetripapplication.components.radio_button.RadioButtonCustom();
        rbBus = new com.organizetrip.organizetripapplication.components.radio_button.RadioButtonCustom();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setBackground(new java.awt.Color(27, 27, 27));

        bg.setBackground(new java.awt.Color(27, 27, 27));

        pnContent.setBackground(new java.awt.Color(27, 27, 27));

        lblTitle1.setBackground(java.awt.Color.white);
        lblTitle1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(3, 139, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("FECHAS DE VIAJE");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecciona la fecha inicial y final");

        txtDate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDate.setText("...");

        lblTitle2.setBackground(java.awt.Color.white);
        lblTitle2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(3, 139, 255));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("TRANSPORTE");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecciona un transporte");

        rbOwn.setBackground(new java.awt.Color(0, 153, 153));
        rbOwn.setForeground(java.awt.Color.white);
        rbOwn.setSelected(true);
        rbOwn.setText("Auto propio");
        rbOwn.setContentAreaFilled(false);
        rbOwn.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rbOwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOwnActionPerformed(evt);
            }
        });

        rbTaxi.setBackground(new java.awt.Color(0, 153, 153));
        rbTaxi.setForeground(java.awt.Color.white);
        rbTaxi.setText("Taxi (+15$)");
        rbTaxi.setContentAreaFilled(false);
        rbTaxi.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rbTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTaxiActionPerformed(evt);
            }
        });

        rbBus.setBackground(new java.awt.Color(0, 153, 153));
        rbBus.setForeground(java.awt.Color.white);
        rbBus.setText("Bus (+25$)");
        rbBus.setContentAreaFilled(false);
        rbBus.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rbBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBusActionPerformed(evt);
            }
        });

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/propio.png"))); // NOI18N

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/taxi.png"))); // NOI18N

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/long.png"))); // NOI18N

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnContentLayout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
            .addGroup(pnContentLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbOwn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGap(173, 173, 173)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbOwn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbOwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOwnActionPerformed
        own = true;
        taxi = false;
        bus = false;
        updateTransport();
    }//GEN-LAST:event_rbOwnActionPerformed

    private void rbTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTaxiActionPerformed
        own = false;
        taxi = true;
        bus = false;
        updateTransport();
    }//GEN-LAST:event_rbTaxiActionPerformed

    private void rbBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBusActionPerformed
        own = false;
        taxi = false;
        bus = true;
        updateTransport();
    }//GEN-LAST:event_rbBusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JPanel pnContent;
    private com.organizetrip.organizetripapplication.components.radio_button.RadioButtonCustom rbBus;
    private com.organizetrip.organizetripapplication.components.radio_button.RadioButtonCustom rbOwn;
    private com.organizetrip.organizetripapplication.components.radio_button.RadioButtonCustom rbTaxi;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
