package com.organizetrip.organizetripapplication.gui;

import java.awt.Color;
import java.awt.Component;

import com.organizetrip.organizetripapplication.classes.UserInfo;

import lombok.Getter;

@SuppressWarnings({"unchecked", "rawtypes"})
@Getter
public class IndicatorPanel extends javax.swing.JPanel {
    private UserInfo userInfo;
    private SummaryPanel summaryPanel;

    /**
     * Creates new form IndicatorPanel
     */
    public IndicatorPanel(String name) {
        // Crea un objeto con la información del usuario
        userInfo = UserInfo.builder().name(name).build();
        summaryPanel = new SummaryPanel(userInfo);

        // Inicializa los componentes
        initComponents();

        // Crea las pestañas del panel slider
        Component[] components = new Component[]{
            new DestinationPanel(userInfo),
            new DatesAndTransportPanel(userInfo),
            new MoneyCompanionAndAccommodationPanel(userInfo),
            new PlacesToVisitPanel(userInfo),
            new ReviewsAndExpectationsPanel(userInfo),
            summaryPanel,
            new FinalScreenPanel()
        };

        // Integr a las pestañas al panel slider
        panelSlider.setSliderComponent(components);
        progressIndicator.initSlider(panelSlider);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressIndicator = new com.organizetrip.organizetripapplication.components.progressindicator.ProgressIndicator();
        panelSlider = new com.organizetrip.organizetripapplication.components.progressindicator.PanelSlider();
        pnButtons = new javax.swing.JPanel();
        btnBack = new com.organizetrip.organizetripapplication.classes.button.Button();
        btnNext = new com.organizetrip.organizetripapplication.classes.button.Button();

        setBackground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(27, 27, 27));

        progressIndicator.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 40, 5, 40));
        progressIndicator.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        progressIndicator.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Destino", "Fechas y Transporte", "Alojamiento", "Lugares", "Opiniones", "Resumen", "Finalizar" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        progressIndicator.setOpaque(false);
        progressIndicator.setProgress(0.0F);
        progressIndicator.setProgressColor(new java.awt.Color(3, 139, 255));
        progressIndicator.setProgressColorGradient(new java.awt.Color(153, 255, 153));
        progressIndicator.setProgressFill(true);

        panelSlider.setOpaque(false);

        pnButtons.setBackground(java.awt.Color.white);
        pnButtons.setOpaque(false);

        btnBack.setBackground(new java.awt.Color(3, 139, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Retroceder");
        btnBack.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(3, 139, 255));
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Siguiente");
        btnNext.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnButtonsLayout = new javax.swing.GroupLayout(pnButtons);
        pnButtons.setLayout(pnButtonsLayout);
        pnButtonsLayout.setHorizontalGroup(
            pnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(684, 684, 684)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnButtonsLayout.setVerticalGroup(
            pnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(progressIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(panelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addComponent(pnButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(progressIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        progressIndicator.previous();
        System.out.println(progressIndicator.getProgress());

        // Styles
        if (progressIndicator.getProgress() <= 6) {
            btnNext.setText("Siguiente");
            btnNext.setBackground(new Color(3, 139, 255));
        }
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        progressIndicator.next();
        System.out.println(userInfo);

        if (progressIndicator.getProgress() == 4) {
            this.summaryPanel.setUserInfoInComponents();
        }

        // Styles
        if (progressIndicator.getProgress() == 5) {
            btnNext.setText("Finalizar");
            btnNext.setBackground(new Color(153,255,153));
            
        } else if (progressIndicator.getProgress() == 6) {
            System.exit(0);
        } else {
            btnNext.setText("Siguiente");
            btnNext.setBackground(new Color(3, 139, 255));
        }
    }//GEN-LAST:event_btnNextMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.organizetrip.organizetripapplication.classes.button.Button btnBack;
    private com.organizetrip.organizetripapplication.classes.button.Button btnNext;
    private javax.swing.JPanel jPanel1;
    private com.organizetrip.organizetripapplication.components.progressindicator.PanelSlider panelSlider;
    private javax.swing.JPanel pnButtons;
    private com.organizetrip.organizetripapplication.components.progressindicator.ProgressIndicator progressIndicator;
    // End of variables declaration//GEN-END:variables
}
