package com.organizetrip.organizetripapplication.gui;

import javax.swing.JPanel;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.CardLayout;

public class MainFrame extends javax.swing.JFrame {
    private CardLayout cardLayout;
    private JPanel containerPanel;
    private String name;

    /**
     * Creates new form FirstFrame
     */
    public MainFrame() {
        name = "Guillermo";

        // Define estilos globales de tipo FlatLaf
        FlatIntelliJLaf.registerCustomDefaultsSource("style");
        FlatIntelliJLaf.setup();

        // Inicializa los paneles
        initPanels();

        // Muéstrame el panel de bienvenida
        showCard("WelcomePanel");

        // Inicializa los componentes
        initComponents();
    }
    
    private void initPanels() {
        cardLayout = new CardLayout();
        containerPanel = new JPanel(cardLayout);
        getContentPane().add(containerPanel);
        
        WelcomePanel welcomePanel = new WelcomePanel(this, name);
        IndicatorPanel indicatorPanel = new IndicatorPanel(name);
        
        containerPanel.add(welcomePanel, "WelcomePanel");
        containerPanel.add(indicatorPanel, "IndicatorPanel");        
    }

    public void showCard(String card) {
        cardLayout.show(containerPanel, card);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planificador de Viajes");
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        bg.setBackground(new java.awt.Color(27, 27, 27));
        bg.setToolTipText("");
        bg.setName("panelBg"); // NOI18N
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle1.setBackground(java.awt.Color.white);
        lblTitle1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 153, 153));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Ejecutar el archivo MainFrame.java");
        bg.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}
