package com.organizetrip.organizetripapplication.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import com.organizetrip.organizetripapplication.classes.UserInfo;

@SuppressWarnings("unused")
public class MoneyCompanionAndAccommodationPanel extends javax.swing.JPanel {
    private UserInfo userInfo;
    private boolean havePlaceToStay;

    /**
     * Creates new form CompanionAndAccommodationPanel
     */
    @SuppressWarnings("rawtypes")
    public MoneyCompanionAndAccommodationPanel(UserInfo userInfo) {
        this.userInfo = userInfo;
        initComponents();
        updatePlaceToStay(true);

        numCompanies.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                JSpinner source = (JSpinner) e.getSource();
                userInfo.setCompanions((int) source.getValue());
            }
        });
        numMoney.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                JSpinner source = (JSpinner) e.getSource();
                userInfo.setBudgetUSD((int) source.getValue());
            }
        });
        cmbNear.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JComboBox cb = (JComboBox) e.getSource();
                String selectedItem = (String) cb.getSelectedItem();
                userInfo.setPlaceToStay(selectedItem);
            }
        });
    }

    private void updatePlaceToStay(boolean havePlaceToStay) {
        if (havePlaceToStay) {
            havePlaceToStay = true;
            rbPlaceYes.setSelected(true);
            rbPlaceNo.setSelected(false);
            // Cmb
            userInfo.setPlaceToStay(null);
            lblNear.setText("Ya cuentas con un alojamiento. No es necesario seleccionar uno.");
            lblNear.setEnabled(false);
            cmbNear.setEnabled(false);
            userInfo.setPlaceToStay("Alojamiento propio");
        } else {
            havePlaceToStay = false;
            rbPlaceYes.setSelected(false);
            rbPlaceNo.setSelected(true);
            // Cmb
            userInfo.setPlaceToStay((String) cmbNear.getSelectedItem());
            lblNear.setText("¡Se detectaron los siguientes alojamientos cercanos a la zona seleccionada!");
            lblNear.setEnabled(true);
            cmbNear.setEnabled(true);
        }
        userInfo.setHavePlaceToStay(havePlaceToStay);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        pnContent = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numMoney = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        rbPlaceNo = new com.organizetrip.organizetripapplication.components.radio_button.RadioButtonCustom();
        rbPlaceYes = new com.organizetrip.organizetripapplication.components.radio_button.RadioButtonCustom();
        numCompanies = new javax.swing.JSpinner();
        cmbNear = new javax.swing.JComboBox<>();
        lblNear = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        bg.setBackground(new java.awt.Color(27, 27, 27));

        pnContent.setBackground(new java.awt.Color(27, 27, 27));

        lblTitle1.setBackground(java.awt.Color.white);
        lblTitle1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(3, 139, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("ACOMPAÑANTES");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("¿Cuántas personas viajan contigo?");

        lblTitle2.setBackground(java.awt.Color.white);
        lblTitle2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(3, 139, 255));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("ALOJAMIENTO");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("¿Cuál es tu máximo presupuesto (COP$)?");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("¿Cuenta con un lugar en particular para su estadía?");

        rbPlaceNo.setBackground(new java.awt.Color(0, 102, 0));
        rbPlaceNo.setForeground(java.awt.Color.white);
        rbPlaceNo.setText("No");
        rbPlaceNo.setContentAreaFilled(false);
        rbPlaceNo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rbPlaceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlaceNoActionPerformed(evt);
            }
        });

        rbPlaceYes.setBackground(new java.awt.Color(0, 102, 0));
        rbPlaceYes.setForeground(java.awt.Color.white);
        rbPlaceYes.setSelected(true);
        rbPlaceYes.setText("Si");
        rbPlaceYes.setContentAreaFilled(false);
        rbPlaceYes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        rbPlaceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlaceYesActionPerformed(evt);
            }
        });

        cmbNear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(COP$126.500 por noche): Ecohostal Yuluka", "(COP$156.000 por noche): Hostal Casa Marina", "(COP$175.800 por noche): B&B Casa Amani", "(COP$182.000 por noche): ApartaHotel Tukasa Rodadero", "(COP$212.100 por noche): Cabaña Condominio Villas del Palmar", "(COP$235.000 por noche): Hotel Playa Mar", "(COP$250.000 por noche): Apartamentos Salazar - Caribe", "(COP$276.400 por noche): Hotel Caribe Rodadero" }));

        lblNear.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblNear.setForeground(new java.awt.Color(0, 153, 0));
        lblNear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNear.setText("Se detectaron los siguientes alojamientos cercanos");

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnContentLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(pnContentLayout.createSequentialGroup()
                                .addComponent(rbPlaceYes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbPlaceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(lblNear)
                            .addComponent(cmbNear, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnContentLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(numCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTitle2)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPlaceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPlaceYes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(lblNear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbNear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblTitle1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numCompanies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbPlaceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlaceNoActionPerformed
        updatePlaceToStay(false);
    }//GEN-LAST:event_rbPlaceNoActionPerformed

    private void rbPlaceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlaceYesActionPerformed
        updatePlaceToStay(true);
    }//GEN-LAST:event_rbPlaceYesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> cmbNear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNear;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JSpinner numCompanies;
    private javax.swing.JSpinner numMoney;
    private javax.swing.JPanel pnContent;
    private com.organizetrip.organizetripapplication.components.radio_button.RadioButtonCustom rbPlaceNo;
    private com.organizetrip.organizetripapplication.components.radio_button.RadioButtonCustom rbPlaceYes;
    // End of variables declaration//GEN-END:variables
}
