package com.organizetrip.organizetripapplication.gui;

import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;

import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;

import com.organizetrip.organizetripapplication.classes.Review;
import com.organizetrip.organizetripapplication.classes.UserInfo;
import com.organizetrip.organizetripapplication.components.ReviewPanel;
import com.organizetrip.organizetripapplication.control.ReviewsControl;

public class ReviewsAndExpectationsPanel extends javax.swing.JPanel {
    // Control
    private final ReviewsControl reviewsControl;
    // Variables globales
    private List<Review> reviews = new ArrayList<>();
    // Variables
    private UserInfo userInfo;
    private int rating;

    /**
     * Creates new form ReviewsAndExpectationsPanel
     */
    public ReviewsAndExpectationsPanel(UserInfo userInfo) {
        reviewsControl = new ReviewsControl();

        this.userInfo = userInfo;
        rating = 1;
        
        // Componentes
        initComponents();
        pnReviews.setLayout(new BoxLayout(pnReviews, BoxLayout.Y_AXIS));
        txtName.setText(userInfo.getName());

        // Diseño de la interfaz de las opiniones
        createReviewsList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        pnContent = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnStar1 = new javax.swing.JButton();
        btnStar2 = new javax.swing.JButton();
        btnStar3 = new javax.swing.JButton();
        btnStar4 = new javax.swing.JButton();
        btnStar5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        scrollPnComment = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JEditorPane();
        btnSendReview = new com.organizetrip.organizetripapplication.classes.button.Button();
        scrollPnReviews = new javax.swing.JScrollPane();
        pnReviews = new javax.swing.JPanel();

        bg.setBackground(new java.awt.Color(27, 27, 27));

        pnContent.setBackground(new java.awt.Color(27, 27, 27));

        lblTitle1.setBackground(java.awt.Color.white);
        lblTitle1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(3, 139, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("OPINIONES Y EXPECTATIVAS");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        txtName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtName.setEnabled(false);
        txtName.setPreferredSize(new java.awt.Dimension(64, 30));

        btnStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/star.png"))); // NOI18N
        btnStar1.setBorder(null);
        btnStar1.setBorderPainted(false);
        btnStar1.setContentAreaFilled(false);
        btnStar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStar1MouseClicked(evt);
            }
        });

        btnStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/star_off.png"))); // NOI18N
        btnStar2.setBorder(null);
        btnStar2.setBorderPainted(false);
        btnStar2.setContentAreaFilled(false);
        btnStar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStar2MouseClicked(evt);
            }
        });

        btnStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/star_off.png"))); // NOI18N
        btnStar3.setBorder(null);
        btnStar3.setBorderPainted(false);
        btnStar3.setContentAreaFilled(false);
        btnStar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStar3MouseClicked(evt);
            }
        });

        btnStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/star_off.png"))); // NOI18N
        btnStar4.setBorder(null);
        btnStar4.setBorderPainted(false);
        btnStar4.setContentAreaFilled(false);
        btnStar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStar4MouseClicked(evt);
            }
        });

        btnStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/star_off.png"))); // NOI18N
        btnStar5.setBorder(null);
        btnStar5.setBorderPainted(false);
        btnStar5.setContentAreaFilled(false);
        btnStar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStar5MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Puntuación:");

        txtArea.setBackground(new java.awt.Color(27, 27, 27));
        txtArea.setBorder(null);
        txtArea.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtArea.setForeground(java.awt.Color.white);
        txtArea.setText("Esperando comentario...");
        txtArea.setToolTipText("");
        txtArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAreaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAreaMouseExited(evt);
            }
        });
        scrollPnComment.setViewportView(txtArea);

        btnSendReview.setBackground(new java.awt.Color(3, 139, 255));
        btnSendReview.setBorder(null);
        btnSendReview.setForeground(java.awt.Color.white);
        btnSendReview.setText("Enviar opinión");
        btnSendReview.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSendReview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendReviewMouseClicked(evt);
            }
        });

        scrollPnReviews.setBackground(new java.awt.Color(43, 43, 43));
        scrollPnReviews.setBorder(null);
        scrollPnReviews.setOpaque(false);

        pnReviews.setBackground(new java.awt.Color(43, 43, 43));
        pnReviews.setAutoscrolls(true);
        pnReviews.setPreferredSize(new java.awt.Dimension(0, 480));
        pnReviews.setRequestFocusEnabled(false);

        javax.swing.GroupLayout pnReviewsLayout = new javax.swing.GroupLayout(pnReviews);
        pnReviews.setLayout(pnReviewsLayout);
        pnReviewsLayout.setHorizontalGroup(
            pnReviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnReviewsLayout.setVerticalGroup(
            pnReviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        scrollPnReviews.setViewportView(pnReviews);

        javax.swing.GroupLayout pnContentLayout = new javax.swing.GroupLayout(pnContent);
        pnContent.setLayout(pnContentLayout);
        pnContentLayout.setHorizontalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnContentLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStar4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStar5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPnComment, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnContentLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSendReview, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPnReviews, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnContentLayout.setVerticalGroup(
            pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnContentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle1)
                .addGap(18, 18, 18)
                .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnContentLayout.createSequentialGroup()
                        .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(scrollPnComment, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSendReview, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPnReviews, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStar1MouseClicked
        rating = 1;
        selectRating();
    }//GEN-LAST:event_btnStar1MouseClicked

    private void btnStar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStar2MouseClicked
        rating = 2;
        selectRating();
    }//GEN-LAST:event_btnStar2MouseClicked

    private void btnStar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStar3MouseClicked
        rating = 3;
        selectRating();
    }//GEN-LAST:event_btnStar3MouseClicked

    private void btnStar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStar4MouseClicked
        rating = 4;
        selectRating();
    }//GEN-LAST:event_btnStar4MouseClicked

    private void btnStar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStar5MouseClicked
        rating = 5;
        selectRating();
    }//GEN-LAST:event_btnStar5MouseClicked

    private void btnSendReviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendReviewMouseClicked
        String name = txtName.getText();
        String text = txtArea.getText().replaceFirst("Esperando comentario...", "");

        // Agrega la opinión a la lista
        reviewsControl.addReview(name, rating, text);

        // Reinicia los controles
        txtName.setText(userInfo.getName());
        rating = 1;
        txtArea.setText("Esperando comentario...");

        // Actualiza la lista de opiniones
        createReviewsList();
    }//GEN-LAST:event_btnSendReviewMouseClicked

    private void createReviewsList() {
        // Recibe la lista de opiniones almacenadas en el archivo reviews.json
        reviews = reviewsControl.getReviews();
        
        // Actualiza la lista de opiniones
        pnReviews.removeAll();
        reviews.forEach(review -> {
            ReviewPanel reviewPanel = new ReviewPanel(review);
            pnReviews.add(reviewPanel);
        });

        // Guarda la lista de reviews que pertenecen al usuario con nombre userInfo.getName()
        List<String> userReviews = new ArrayList<>();
        reviews.forEach(review -> {
            if (review.getName().equals(userInfo.getName())) {
                userReviews.add("[" + review.getDate() + " - " + review.getTime() + "] (" + review.getRating() + " estrellas): " + review.getComment());
            }
        });
        userInfo.setReviews(userReviews);
        
        // Actualiza la interfaz
        updateScrollPane();
    }

    private void updateScrollPane() {
        pnReviews.revalidate();
        pnReviews.repaint();
    
        // Calcular el tamaño preferido del panel basado en sus componentes
        int width = pnReviews.getPreferredSize().width;
        int height = 0;
        for (Component comp : pnReviews.getComponents()) {
            height += comp.getPreferredSize().height;
        }
        pnReviews.setPreferredSize(new Dimension(width, height));
    
        // Avisar al JScrollPane que verifique nuevamente si necesita mostrar barras de desplazamiento
        scrollPnReviews.revalidate();
        scrollPnReviews.repaint();
    }

    private void txtAreaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaMouseEntered
    if (txtArea.getText().equals("Esperando comentario...")) {
        txtArea.setText("");
    }
    }//GEN-LAST:event_txtAreaMouseEntered

    private void txtAreaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAreaMouseExited
        if (txtArea.getText().equals("")) {
            txtArea.setText("Esperando comentario...");
        }
    }//GEN-LAST:event_txtAreaMouseExited

    private void selectRating() {
        List<JButton> stars = new ArrayList<>(
            List.of(btnStar1, btnStar2, btnStar3, btnStar4, btnStar5)
        );

        stars.forEach(star -> star.setIcon(new ImageIcon(getClass().getResource("/assets/images/star_off.png"))));

        for (int i = 0; i < rating; i++) {
            stars.get(i).setIcon(new ImageIcon(getClass().getResource("/assets/images/star.png")));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private com.organizetrip.organizetripapplication.classes.button.Button btnSendReview;
    private javax.swing.JButton btnStar1;
    private javax.swing.JButton btnStar2;
    private javax.swing.JButton btnStar3;
    private javax.swing.JButton btnStar4;
    private javax.swing.JButton btnStar5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnReviews;
    private javax.swing.JScrollPane scrollPnComment;
    private javax.swing.JScrollPane scrollPnReviews;
    private javax.swing.JEditorPane txtArea;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
