package com.organizetrip.organizetripapplication.gui;

public class WelcomePanel extends javax.swing.JPanel {
    private MainFrame mainFrame;

    /**
     * Creates new form WelcomePanel
     */
    public WelcomePanel(MainFrame mainFrame, String name) {
        this.mainFrame = mainFrame;
        initComponents();
        lblTitle1.setText("¡Bienvenido " + name + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblInfo1 = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        button1 = new com.organizetrip.organizetripapplication.classes.button.Button();

        bg.setBackground(new java.awt.Color(27, 27, 27));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/undraw_hello.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 190));

        lblTitle1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(3, 139, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("¡Bienvenido!");
        lblTitle1.setToolTipText("");
        bg.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1000, -1));

        lblTitle2.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(3, 139, 255));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("¿Listo para viajar?");
        lblTitle2.setToolTipText("");
        bg.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        lblInfo1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lblInfo1.setForeground(java.awt.Color.white);
        lblInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo1.setText("Planifica tu viaje de la mejor manera y");
        bg.add(lblInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 350, 30));

        lblInfo2.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        lblInfo2.setForeground(java.awt.Color.white);
        lblInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo2.setText("crea tu viaje ideal, adaptándose a tus preferencias y presupuesto.");
        bg.add(lblInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        button1.setBackground(new java.awt.Color(3, 139, 255));
        button1.setForeground(java.awt.Color.white);
        button1.setText("ESTOY LISTO");
        button1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        bg.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        mainFrame.showCard("IndicatorPanel");
    }//GEN-LAST:event_button1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private com.organizetrip.organizetripapplication.classes.button.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    // End of variables declaration//GEN-END:variables
}
